# Generated by Django 3.2 on 2024-08-28 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sourcedb_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedb',
            name='original_curator_db',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
