# Generated by Django 3.2 on 2025-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240828_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='production_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('scientific_name', 'production_name', 'taxon_id')},
        ),
    ]
